### USERS LOGIN/REGISTER

###
POST http://localhost:3000/api/register
Content-Type: application/json

{
"nickname": "controller",
"email": "ctrl@ctrl.lt",
"password": "secret123"
}

###
POST http://localhost:3000/api/login
Content-Type: application/json

{
"email": "kiesa@kestis.lt",
"password": "secret123"
}

### QUESTIONS
###
GET http://localhost:3000/api/question

###
POST http://localhost:3000/api/question
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY1ODkyMTY0NywiZXhwIjoxNjU4OTMyNDQ3fQ.Ao4ACRfO_4s5RFGFj3qcsfmFKLClZNH822vX3s8n1Dg

{
  "title": "UserId question another one",
  "content": "UserID checking different token"
}

###
PATCH http://localhost:3000/api/question/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTY1ODg5OTc4NSwiZXhwIjoxNjU4OTEwNTg1fQ.Xk5qbH6korc9uNt4HYZAs_M_vuntNbWchdrJdXAQXvg

{
  "title": "Controller added TESTING PATCH",
  "content": "rest rest tetsing after moving to controller TESTING PATCH"
}

###
DELETE http://localhost:3000/api/question/6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY1ODkyMTY0NywiZXhwIjoxNjU4OTMyNDQ3fQ.Ao4ACRfO_4s5RFGFj3qcsfmFKLClZNH822vX3s8n1Dg

